import { Poppins } from "next/font/google";
import "../globals.css";
import { Providers } from "../../lib/providers";
import Navbar from "@/components/navbar";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <div className="flex flex-col min-h-screen bg-background text-foreground">
            <Navbar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
